Repository deep5050/radio-active, pull requests merged in 2023-09, with the labels that each got.

#28 volume flag added to help table
  radioactive/help.py
Labels: size/XS

#31 2.5.0
  CHANGELOG.md
  README.md
  radioactive/__main__.py
  radioactive/alias.py
  radioactive/app.py
  radioactive/args.py
  radioactive/last_station.py
  radioactive/player.py
  requirements
Labels: size/L

#41 2.5.1
  .vscode/settings.json
  CHANGELOG.md
  radioactive/__main__.py
  radioactive/alias.py
  radioactive/app.py
  radioactive/handler.py
  radioactive/help.py
  radioactive/player.py
Labels: size/L

#44 2.5.2
  .gitignore
  CHANGELOG.md
  LICENSE
  MANIFEST.in
  Makefile
  README.md
  radioactive/__main__.py
  radioactive/app.py
  radioactive/args.py
  radioactive/help.py
  radioactive/player.py
  requirements-dev.txt
  requirements.txt
  setup.cfg
  setup.py
Labels: size/L

#50 2.6.0
  .editorconfig
  .vscode/settings.json
  CHANGELOG.md
  Makefile
  README.md
  app.drawio
  radioactive/__init__.py
  radioactive/__main__.py
  radioactive/alias.py
  radioactive/app.py
  radioactive/args.py
  radioactive/handler.py
  radioactive/help.py
  radioactive/last_station.py
  radioactive/player.py
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: size/XL

#56 2.7.0
  .gitignore
  .vscode/settings.json
  CHANGELOG.md
  Makefile
  README.md
  install.sh
  radioactive/__main__.py
  radioactive/alias.py
  radioactive/app.py
  radioactive/args.py
  radioactive/handler.py
  radioactive/help.py
  radioactive/recorder.py
  radioactive/utilities.py
  requirements.txt
Labels: size/XXL
